// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ObjectsColumns holds the columns for the "objects" table.
	ObjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "object_name", Type: field.TypeString},
		{Name: "content_type", Type: field.TypeString},
		{Name: "object_location", Type: field.TypeUint8},
		{Name: "object_size", Type: field.TypeInt64},
		{Name: "object_sha256", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ObjectsTable holds the schema information for the "objects" table.
	ObjectsTable = &schema.Table{
		Name:       "objects",
		Columns:    ObjectsColumns,
		PrimaryKey: []*schema.Column{ObjectsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "object_id",
				Unique:  false,
				Columns: []*schema.Column{ObjectsColumns[0]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ObjectsTable,
	}
)

func init() {
}
