// 定义我们接口的版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: proto/app/app.proto

// 定义包名称

package app

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 对象元信息
type NoeMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 节点ID
}

func (x *NoeMeta) Reset() {
	*x = NoeMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_app_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoeMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoeMeta) ProtoMessage() {}

func (x *NoeMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_app_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoeMeta.ProtoReflect.Descriptor instead.
func (*NoeMeta) Descriptor() ([]byte, []int) {
	return file_proto_app_app_proto_rawDescGZIP(), []int{0}
}

func (x *NoeMeta) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除响应事件
type DeleteNodeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id bool `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 对象ID
}

func (x *DeleteNodeResp) Reset() {
	*x = DeleteNodeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_app_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeResp) ProtoMessage() {}

func (x *DeleteNodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_app_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeResp.ProtoReflect.Descriptor instead.
func (*DeleteNodeResp) Descriptor() ([]byte, []int) {
	return file_proto_app_app_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteNodeResp) GetId() bool {
	if x != nil {
		return x.Id
	}
	return false
}

type GetNodeInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*CardInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"` // 对象ID和所属应用
}

func (x *GetNodeInfoReq) Reset() {
	*x = GetNodeInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_app_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodeInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoReq) ProtoMessage() {}

func (x *GetNodeInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_app_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoReq.ProtoReflect.Descriptor instead.
func (*GetNodeInfoReq) Descriptor() ([]byte, []int) {
	return file_proto_app_app_proto_rawDescGZIP(), []int{2}
}

func (x *GetNodeInfoReq) GetInfos() []*CardInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

// 获取节点信息
type GetNodeInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []*CardInfo `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"` // 卡片信息列表
}

func (x *GetNodeInfoResp) Reset() {
	*x = GetNodeInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_app_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodeInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoResp) ProtoMessage() {}

func (x *GetNodeInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_app_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoResp.ProtoReflect.Descriptor instead.
func (*GetNodeInfoResp) Descriptor() ([]byte, []int) {
	return file_proto_app_app_proto_rawDescGZIP(), []int{3}
}

func (x *GetNodeInfoResp) GetCards() []*CardInfo {
	if x != nil {
		return x.Cards
	}
	return nil
}

//  卡片信息
type CardInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId int64  `protobuf:"varint,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"` // 节点ID
	App    string `protobuf:"bytes,2,opt,name=App,proto3" json:"App,omitempty"`        // 卡片所属应用
	Info   string `protobuf:"bytes,3,opt,name=Info,proto3" json:"Info,omitempty"`      // 卡片信息
}

func (x *CardInfo) Reset() {
	*x = CardInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_app_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardInfo) ProtoMessage() {}

func (x *CardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_app_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardInfo.ProtoReflect.Descriptor instead.
func (*CardInfo) Descriptor() ([]byte, []int) {
	return file_proto_app_app_proto_rawDescGZIP(), []int{4}
}

func (x *CardInfo) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *CardInfo) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *CardInfo) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_proto_app_app_proto protoreflect.FileDescriptor

var file_proto_app_app_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x70, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x19, 0x0a, 0x07, 0x4e, 0x6f,
	0x65, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x20, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x02, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x05, 0x69, 0x6e, 0x66,
	0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43,
	0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x36,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x23, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x22, 0x48, 0x0a, 0x08, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x70,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x41, 0x70, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f,
	0x32, 0x70, 0x0a, 0x03, 0x41, 0x70, 0x70, 0x12, 0x2f, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x6f, 0x65, 0x4d,
	0x65, 0x74, 0x61, 0x1a, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65,
	0x74, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x42, 0x13, 0x5a, 0x11, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x61, 0x70, 0x70, 0x2f,
	0x61, 0x70, 0x69, 0x3b, 0x61, 0x70, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_app_app_proto_rawDescOnce sync.Once
	file_proto_app_app_proto_rawDescData = file_proto_app_app_proto_rawDesc
)

func file_proto_app_app_proto_rawDescGZIP() []byte {
	file_proto_app_app_proto_rawDescOnce.Do(func() {
		file_proto_app_app_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_app_app_proto_rawDescData)
	})
	return file_proto_app_app_proto_rawDescData
}

var file_proto_app_app_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_app_app_proto_goTypes = []interface{}{
	(*NoeMeta)(nil),         // 0: api.NoeMeta
	(*DeleteNodeResp)(nil),  // 1: api.DeleteNodeResp
	(*GetNodeInfoReq)(nil),  // 2: api.GetNodeInfoReq
	(*GetNodeInfoResp)(nil), // 3: api.GetNodeInfoResp
	(*CardInfo)(nil),        // 4: api.CardInfo
}
var file_proto_app_app_proto_depIdxs = []int32{
	4, // 0: api.GetNodeInfoReq.infos:type_name -> api.CardInfo
	4, // 1: api.GetNodeInfoResp.cards:type_name -> api.CardInfo
	0, // 2: api.App.DeleteNode:input_type -> api.NoeMeta
	2, // 3: api.App.GetNodeInfo:input_type -> api.GetNodeInfoReq
	1, // 4: api.App.DeleteNode:output_type -> api.DeleteNodeResp
	3, // 5: api.App.GetNodeInfo:output_type -> api.GetNodeInfoResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_app_app_proto_init() }
func file_proto_app_app_proto_init() {
	if File_proto_app_app_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_app_app_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoeMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_app_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNodeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_app_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodeInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_app_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodeInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_app_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_app_app_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_app_app_proto_goTypes,
		DependencyIndexes: file_proto_app_app_proto_depIdxs,
		MessageInfos:      file_proto_app_app_proto_msgTypes,
	}.Build()
	File_proto_app_app_proto = out.File
	file_proto_app_app_proto_rawDesc = nil
	file_proto_app_app_proto_goTypes = nil
	file_proto_app_app_proto_depIdxs = nil
}
