// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"index.data/ent/object"
	"index.data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	objectFields := schema.Object{}.Fields()
	_ = objectFields
	// objectDescCreatedAt is the schema descriptor for created_at field.
	objectDescCreatedAt := objectFields[6].Descriptor()
	// object.DefaultCreatedAt holds the default value on creation for the created_at field.
	object.DefaultCreatedAt = objectDescCreatedAt.Default.(func() time.Time)
	// objectDescUpdatedAt is the schema descriptor for updated_at field.
	objectDescUpdatedAt := objectFields[7].Descriptor()
	// object.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	object.DefaultUpdatedAt = objectDescUpdatedAt.Default.(time.Time)
	// object.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	object.UpdateDefaultUpdatedAt = objectDescUpdatedAt.UpdateDefault.(func() time.Time)
}
