// 定义我们接口的版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: proto/data/data.proto

// 定义包名称

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 对象元信息
type ObjectMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`   // 对象ID
	Msg string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"` // 额外信息
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_data_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectMeta) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ObjectMeta) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 上传对象的信息
type ObjectPutInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"` // 文件名称
	Offset   int64  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`    // 偏移量
	Size     int64  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`        // 文件大小
	Data     []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`         // 流式上传的内容
}

func (x *ObjectPutInfo) Reset() {
	*x = ObjectPutInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_data_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectPutInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectPutInfo) ProtoMessage() {}

func (x *ObjectPutInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectPutInfo.ProtoReflect.Descriptor instead.
func (*ObjectPutInfo) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectPutInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ObjectPutInfo) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ObjectPutInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ObjectPutInfo) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取对象的信息
type ObjectInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info        *ObjectPutInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	ContentType string         `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // 文件类型
}

func (x *ObjectInfo) Reset() {
	*x = ObjectInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_data_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectInfo) ProtoMessage() {}

func (x *ObjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectInfo.ProtoReflect.Descriptor instead.
func (*ObjectInfo) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectInfo) GetInfo() *ObjectPutInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *ObjectInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// 删除对象返回结果
type UpdateObjectResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 是否操作成功
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`        // 额外信息
}

func (x *UpdateObjectResp) Reset() {
	*x = UpdateObjectResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_data_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateObjectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateObjectResp) ProtoMessage() {}

func (x *UpdateObjectResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateObjectResp.ProtoReflect.Descriptor instead.
func (*UpdateObjectResp) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateObjectResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UpdateObjectResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 获取文本对象返回
type GetTextResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List map[string]*TextInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 返回结果列表
}

func (x *GetTextResp) Reset() {
	*x = GetTextResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_data_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTextResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextResp) ProtoMessage() {}

func (x *GetTextResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTextResp.ProtoReflect.Descriptor instead.
func (*GetTextResp) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{4}
}

func (x *GetTextResp) GetList() map[string]*TextInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 文本信息
type TextInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // 文本名字
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 文本内容
}

func (x *TextInfo) Reset() {
	*x = TextInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_data_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextInfo) ProtoMessage() {}

func (x *TextInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextInfo.ProtoReflect.Descriptor instead.
func (*TextInfo) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{5}
}

func (x *TextInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TextInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 更新文件信息
type UpdateTextInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // 资源ID
	Info *TextInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"` // 文本信息
}

func (x *UpdateTextInfo) Reset() {
	*x = UpdateTextInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_data_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTextInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTextInfo) ProtoMessage() {}

func (x *UpdateTextInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTextInfo.ProtoReflect.Descriptor instead.
func (*UpdateTextInfo) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTextInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTextInfo) GetInfo() *TextInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// 分片上传文件
type PutObjectChunkReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalChunk int32  `protobuf:"varint,1,opt,name=totalChunk,proto3" json:"totalChunk,omitempty"` // 总分片数
	Current    int32  `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`       // 当前为第几个分片（从1开始）
	TotalSize  int64  `protobuf:"varint,3,opt,name=totalSize,proto3" json:"totalSize,omitempty"`   // 总文件大小
	Size       int64  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`             // 当前分片数据的大小
	Md5        string `protobuf:"bytes,5,opt,name=md5,proto3" json:"md5,omitempty"`                // 文件MD5值
	Name       string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`              // 文件名字
	Data       []byte `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`              // 分片数据
}

func (x *PutObjectChunkReq) Reset() {
	*x = PutObjectChunkReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_data_data_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutObjectChunkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutObjectChunkReq) ProtoMessage() {}

func (x *PutObjectChunkReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutObjectChunkReq.ProtoReflect.Descriptor instead.
func (*PutObjectChunkReq) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{7}
}

func (x *PutObjectChunkReq) GetTotalChunk() int32 {
	if x != nil {
		return x.TotalChunk
	}
	return 0
}

func (x *PutObjectChunkReq) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *PutObjectChunkReq) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *PutObjectChunkReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PutObjectChunkReq) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *PutObjectChunkReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PutObjectChunkReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 分片上传文件返回
type PutObjectChunkResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receive int64  `protobuf:"varint,1,opt,name=receive,proto3" json:"receive,omitempty"` // 当前总计接收了多少文件
	Status  bool   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`   // 当前接收状态是否正常
	Msg     string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`          // 错误信息
	Id      string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`            // 传输完成的后对象ID
}

func (x *PutObjectChunkResp) Reset() {
	*x = PutObjectChunkResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_data_data_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutObjectChunkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutObjectChunkResp) ProtoMessage() {}

func (x *PutObjectChunkResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutObjectChunkResp.ProtoReflect.Descriptor instead.
func (*PutObjectChunkResp) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{8}
}

func (x *PutObjectChunkResp) GetReceive() int64 {
	if x != nil {
		return x.Receive
	}
	return 0
}

func (x *PutObjectChunkResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *PutObjectChunkResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PutObjectChunkResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 获取文件的下载链接
type GetObjectDownloadLinkResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Links map[string]string `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 下载链接
}

func (x *GetObjectDownloadLinkResp) Reset() {
	*x = GetObjectDownloadLinkResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_data_data_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetObjectDownloadLinkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectDownloadLinkResp) ProtoMessage() {}

func (x *GetObjectDownloadLinkResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectDownloadLinkResp.ProtoReflect.Descriptor instead.
func (*GetObjectDownloadLinkResp) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{9}
}

func (x *GetObjectDownloadLinkResp) GetLinks() map[string]string {
	if x != nil {
		return x.Links
	}
	return nil
}

var File_proto_data_data_proto protoreflect.FileDescriptor

var file_proto_data_data_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x2e, 0x0a, 0x0a,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x6b, 0x0a, 0x0d,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x75, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x57, 0x0a, 0x0a, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x50, 0x75, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x3c, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x85, 0x01, 0x0a, 0x0b, 0x67, 0x65, 0x74, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x2e, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x65, 0x74, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x1a, 0x46, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x38, 0x0a, 0x08, 0x54, 0x65, 0x78, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x22, 0x43, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0xb9, 0x01, 0x0a, 0x11, 0x50, 0x75, 0x74, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x64, 0x35, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x68, 0x0a, 0x12, 0x50, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x96, 0x01,
	0x0a, 0x19, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x05, 0x6c,
	0x69, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x1a, 0x38, 0x0a, 0x0a,
	0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xc3, 0x03, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x2f, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x0f, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x30, 0x01,
	0x12, 0x32, 0x0a, 0x09, 0x50, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x75, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x1a, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65,
	0x74, 0x61, 0x28, 0x01, 0x12, 0x36, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x07,
	0x47, 0x65, 0x74, 0x54, 0x65, 0x78, 0x74, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67,
	0x65, 0x74, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x0a, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x12, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x15, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x29, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x54, 0x65, 0x78, 0x74, 0x12,
	0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12,
	0x41, 0x0a, 0x0e, 0x70, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x12, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x50, 0x75, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x48, 0x0a, 0x15, 0x67, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x0f, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x1a, 0x1e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x42, 0x15, 0x5a, 0x13,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x64,
	0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_data_data_proto_rawDescOnce sync.Once
	file_proto_data_data_proto_rawDescData = file_proto_data_data_proto_rawDesc
)

func file_proto_data_data_proto_rawDescGZIP() []byte {
	file_proto_data_data_proto_rawDescOnce.Do(func() {
		file_proto_data_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_data_data_proto_rawDescData)
	})
	return file_proto_data_data_proto_rawDescData
}

var file_proto_data_data_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_data_data_proto_goTypes = []interface{}{
	(*ObjectMeta)(nil),                // 0: api.ObjectMeta
	(*ObjectPutInfo)(nil),             // 1: api.ObjectPutInfo
	(*ObjectInfo)(nil),                // 2: api.ObjectInfo
	(*UpdateObjectResp)(nil),          // 3: api.UpdateObjectResp
	(*GetTextResp)(nil),               // 4: api.getTextResp
	(*TextInfo)(nil),                  // 5: api.TextInfo
	(*UpdateTextInfo)(nil),            // 6: api.UpdateTextInfo
	(*PutObjectChunkReq)(nil),         // 7: api.PutObjectChunkReq
	(*PutObjectChunkResp)(nil),        // 8: api.PutObjectChunkResp
	(*GetObjectDownloadLinkResp)(nil), // 9: api.GetObjectDownloadLinkResp
	nil,                               // 10: api.getTextResp.ListEntry
	nil,                               // 11: api.GetObjectDownloadLinkResp.LinksEntry
}
var file_proto_data_data_proto_depIdxs = []int32{
	1,  // 0: api.ObjectInfo.info:type_name -> api.ObjectPutInfo
	10, // 1: api.getTextResp.list:type_name -> api.getTextResp.ListEntry
	5,  // 2: api.UpdateTextInfo.info:type_name -> api.TextInfo
	11, // 3: api.GetObjectDownloadLinkResp.links:type_name -> api.GetObjectDownloadLinkResp.LinksEntry
	5,  // 4: api.getTextResp.ListEntry.value:type_name -> api.TextInfo
	0,  // 5: api.Data.GetObject:input_type -> api.ObjectMeta
	1,  // 6: api.Data.PutObject:input_type -> api.ObjectPutInfo
	0,  // 7: api.Data.DeleteObject:input_type -> api.ObjectMeta
	0,  // 8: api.Data.GetText:input_type -> api.ObjectMeta
	6,  // 9: api.Data.UpdateText:input_type -> api.UpdateTextInfo
	5,  // 10: api.Data.AddText:input_type -> api.TextInfo
	7,  // 11: api.Data.putObjectChunk:input_type -> api.PutObjectChunkReq
	0,  // 12: api.Data.getObjectDownloadLink:input_type -> api.ObjectMeta
	2,  // 13: api.Data.GetObject:output_type -> api.ObjectInfo
	0,  // 14: api.Data.PutObject:output_type -> api.ObjectMeta
	3,  // 15: api.Data.DeleteObject:output_type -> api.UpdateObjectResp
	4,  // 16: api.Data.GetText:output_type -> api.getTextResp
	3,  // 17: api.Data.UpdateText:output_type -> api.UpdateObjectResp
	0,  // 18: api.Data.AddText:output_type -> api.ObjectMeta
	8,  // 19: api.Data.putObjectChunk:output_type -> api.PutObjectChunkResp
	9,  // 20: api.Data.getObjectDownloadLink:output_type -> api.GetObjectDownloadLinkResp
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_data_data_proto_init() }
func file_proto_data_data_proto_init() {
	if File_proto_data_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_data_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_data_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectPutInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_data_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_data_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateObjectResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_data_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTextResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_data_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_data_data_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTextInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_data_data_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutObjectChunkReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_data_data_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutObjectChunkResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_data_data_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetObjectDownloadLinkResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_data_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_data_data_proto_goTypes,
		DependencyIndexes: file_proto_data_data_proto_depIdxs,
		MessageInfos:      file_proto_data_data_proto_msgTypes,
	}.Build()
	File_proto_data_data_proto = out.File
	file_proto_data_data_proto_rawDesc = nil
	file_proto_data_data_proto_goTypes = nil
	file_proto_data_data_proto_depIdxs = nil
}
