// Code generated by entc, DO NOT EDIT.

package object

import (
	"time"
)

const (
	// Label holds the string label denoting the object type in the database.
	Label = "object"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldObjectName holds the string denoting the object_name field in the database.
	FieldObjectName = "object_name"
	// FieldContentType holds the string denoting the content_type field in the database.
	FieldContentType = "content_type"
	// FieldObjectLocation holds the string denoting the object_location field in the database.
	FieldObjectLocation = "object_location"
	// FieldObjectSize holds the string denoting the object_size field in the database.
	FieldObjectSize = "object_size"
	// FieldObjectSha256 holds the string denoting the object_sha256 field in the database.
	FieldObjectSha256 = "object_sha256"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the object in the database.
	Table = "objects"
)

// Columns holds all SQL columns for object fields.
var Columns = []string{
	FieldID,
	FieldObjectName,
	FieldContentType,
	FieldObjectLocation,
	FieldObjectSize,
	FieldObjectSha256,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
